# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            Vero Virtual Machine
tagline:          ''
url:              https://verovm.github.io
shorturl:         verovm.github.io

paginate:         1

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
